### PR TITLE
Travis setup for test automation

### PR DESCRIPTION
**Pull request by sujith42**

### CODE REVIEW

**Comment by takanokage** [comment]
how is this PR different from the one I just merged?
Please do a re-basing of your fork (now and before any PR), I'm assuming that I've already merged most of this.

**Comment by sujith42** [comment]
Yeah almost some except for small change in .yml file which is not needed
now , As u said there is need to virtual env.

**Comment by takanokage** [comment]
well, please go ahead and rebase and let's see what's left after. ;)

**Comment by takanokage** [comment]
oh, after the rebase you'll notice a few changes in the code, particularly I've added docstrings to methods and modules. your immediate task after this PR is to do the same for the unit tests - will help me and others to understand what you're doing.

**Comment by sujith42** [comment]
Did you  find any useful  changes for my new PR ?

**Comment by takanokage** [comment]
Yep, thanks!
No worries, I picked up everything you did and I'm preparing more for you to do.

**Comment by sujith42** [comment]
Thanks. I am adding docstrings to unitests now . I will create a new PR in
10 to 15 mins .

On 10 Oct 2018 10:18, "Dan Petre" <notifications@github.com> wrote:

Yep, thanks!
No worries, I picked up everything you did and I'm preparing more for you
to do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/takanokage/blocksWorld/pull/4#issuecomment-428656555>,
or mute the thread

**Comment by takanokage** [comment]
oh, if you mean the previous PR.
On this one more than anything I really want you to learn how to rebase you fork. The idea is that while you are working the main repo can accept changes from other people too. It's best practice for you to get the latest changes from the main repo and handle any differences before submitting a PR.

**Comment by takanokage** [comment]
Also, if using email to reply please delete all history messages from the email.
Otherwise the message board gets cluttered with duplicate messages.

**Comment by takanokage** [comment]
First things first: let's address this PR. Later you can look at docstrings.

**Comment by sujith42** [comment]
Oh gosh!!!! Unfortunately , I thought rebase is something to fork again. I
have deleted my repo and forked ur repo .

**Comment by sujith42** [comment]
Anyways, I made a PR for changes in .yml file before deleting my repo.

**Comment by takanokage** [comment]
that's always good experience. no worries, I'm sure there's either a way to recover your previous stuff or simply rewrite it.

**Comment by takanokage** [comment]
Anyway, I could save your stuff from the current PR but I won't. We don't need the xml file for the CI and we don't need venv. I'm going to handle the Travis CI integration.

**Comment by sujith42** [comment]
I will create a branch now and then compare by pushing the contents from my system (older repo). Does it works ?

**Comment by takanokage** [comment]
Go ahead with the docstrings.
Also, I just built the pip package and tried to run the tests and couldn't run them. One of the issues is that I can't pip install unittest. Secondly I'm not sure we really need this external package: please make a case for why we need it. ;) Thanks!

**Comment by takanokage** [comment]
To answer your question: yes, that works. That's pretty much a rebase only done in a very convoluted way :). I'm not going to integrate this PR though, I don't want the extra xml and venv.

**Pull request closed without merging**
